// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeYo3he-OHCBCxbC8ZH6vIYySRbM6l2eE',
    appId: '1:657280713311:web:675e3ea0e0671b73a0d1ea',
    messagingSenderId: '657280713311',
    projectId: 'awasapp-987a5',
    authDomain: 'awasapp-987a5.firebaseapp.com',
    storageBucket: 'awasapp-987a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqvyeZaf0ah7oKrsZE_-uJDcGKFHajvPk',
    appId: '1:657280713311:android:47609051d27acc0ba0d1ea',
    messagingSenderId: '657280713311',
    projectId: 'awasapp-987a5',
    storageBucket: 'awasapp-987a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjGmiA45exiPhhp3z3-TWTQUr1C6OzjuY',
    appId: '1:657280713311:ios:b61b27ffdb32e784a0d1ea',
    messagingSenderId: '657280713311',
    projectId: 'awasapp-987a5',
    storageBucket: 'awasapp-987a5.firebasestorage.app',
    iosBundleId: 'com.example.awasApp',
  );
}
